### ISSUE TITLE
Plugin is incompatible with Phpstorm 2017.1.2

### ISSUE THREAD

**Issue by radonthetyrant** [elfuegobiz/intellij-gitea-plugin#5]
Hello,
I couldn't find the plugin from inside the plugin browser, so i tried to install the latest version 1.3 manually from disk. I then see the following error message:

"Plugin 'Gitea issues plugin' is incompatible with this installation"

Version Info of my Phpstorm installation:
```
PhpStorm 2017.1.2
Build #PS-171.4249.3, built on April 12, 2017
JRE: 1.8.0_112-release-736-b16 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by elfuegobiz** [comment]
You should update your PhpStorm version as the plugin is compatible with versions 173 and higher, and your version is 171, as I can see.
