### ISSUE TITLE
How is supposed to work ?

### ISSUE THREAD

**Issue by protheusfr** [elfuegobiz/intellij-gitea-plugin#6]
I've installed the plugin in Intellij 2018.2, after restart nothing appear : 

- No Gitea toolbar (like Youtrack)
- Gitea button in Issue Navigation

Then, how to use the plugin ?

**Comment by elfuegobiz** [comment]
Tools -> Tasks & Contexts -> Configure Servers -> + Add Server -> Gitea

**Comment by protheusfr** [comment]
Thank you, the url must be only the base URL of gitea server or must include project url ?
